version: "2"
services:
  ubuntu-xenial:
    privileged: true
    build: 
      context: .
      dockerfile: ubuntu-xenial.Dockerfile
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /home/saltstack:/srv/salt
      - /home/pillar:/srv/pillar
      # - ./srv/salt:/srv/salt
      # - ./srv/pillar:/srv/pillar
     hostname: 'hostname.com'
